job1:
  stage: .pre
  script:
    - ls -la
    - echo "olo1" > olo1
  artifacts:
    expire_in: 2min
    public: false
    paths:
      - olo1

job2:
  script:
    - ls -la
    - cat olo1


job3:
  stage: .post
  script:
    - ls -la
    - echo "" > olo1
  artifacts:
    expire_in: 2min
    paths:
      - olo1
